### PR TITLE
Support QC collection

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by apmasell** [comment]
please retest this

**Comment by apmasell** [comment]
retest this please

**Comment by apmasell** [comment]
retest this please

**Comment by iainrb** [comment]
Code changes look fine. Out of curiosity, what does the file `workflow-chromium_mkfastq.iml` do?

**Comment by apmasell** [comment]
It's the file produced by IntelliJ.

**Comment by apmasell** [comment]
Flattened this mess and removed that erroneous IntelliJ file.

**Pull request merged**
